### ISSUE TITLE
Implementar validação CSRF para métodos POST

### ISSUE THREAD

**Issue by SteffanoP** [Engenharia-de-Software-UFRPE/lanterna-verde#18]
Com as recentes implementações em #9 e também as de #17, foi verificado uma brecha de segurança para ataques do tipo _Cross-Site Request Forgery_ (CSRF), devido à exceção imposta ao método de verificação CSRF em métodos POST. 

Dessa forma, devido a esse tipo de _bypass_ os métodos do tipo POST poderão ser explorados por essa brecha de segurança, sendo necessário uma verificação de token CSRF que é armazenado pelo navegador durante a autenticação. Logo, todo método POST deve possuir o token de CSRF e o **back-end** deve estar preparado para verificar o `csrf_token` do navegador e permitir a continuidade do método POST no back-end.

**Comment by ronaldo26rodrigues** [comment]
Estive fazendo uns testes e percebi que o csrftoken pode estar associado às credenciais de autenticação do usuário, então a rota de login sempre recebe um token diferente, que não é validado pelo Django (não sei se isso também poderia ser um problema de front :P). Nesse caso a melhor prática seria usar a tag `@csrf_exempt` na view login?

**Comment by SteffanoP** [comment]
> Estive fazendo uns testes e percebi que o csrftoken pode estar associado às credenciais de autenticação do usuário, então a rota de login sempre recebe um token diferente, que não é validado pelo Django (não sei se isso também poderia ser um problema de front :P). Nesse caso a melhor prática seria usar a tag `@csrf_exempt` na view login?

@ronaldo26rodrigues eu vou trabalhar nisso com o back-end, te mantenho informado sobre a melhor forma de implementar uma solução para o problema.
