### ISSUE TITLE
Navegação entre telas

### ISSUE THREAD

**Issue by Koda-ms** [Engenharia-de-Software-UFRPE/lanterna-verde#32]
Oi, @Engenharia-de-Software-UFRPE/empresa-frontend ! Eu estava completando as rotas aqui entre a tela _Home_ e a de _Cadastro da Empresa_ e gostaria de pedir mencionar duas coisas: 

1º Agora que a _Home_ já está na _main_, vocês podem direcionar as suas telas para voltarem à _Home_ toda vez ao clicar na nossa logo. No link abaixo é onde eu vi que isso também pode ser feito. Mas, para generelizar, vocês podem esse caminho à toda tela com a logo na Navbar. 😉

2º Na tela de _Cadastro_ tem um probleminha com a imgem do selo no canto esquerdo. Ele está distorcido na altura, como pode ser visto no anexo abaixo. 

É isto! ^^

![Captura de tela 2022-09-01 151057](https://user-images.githubusercontent.com/66442236/187983847-146a4763-bb8a-4e0c-8eba-07a4e665f930.png)

https://github.com/Engenharia-de-Software-UFRPE/lanterna-verde/blob/dbcecd5b8b48d2e22694977f4f9a5d45337efe15/Frontend/src/components/company-components/company-basic-header/CompanyBasicHeader.js#L9

**Comment by SteffanoP** [comment]
Problema resolvido em #74.
