### ISSUE TITLE
Criar Layout das Perguntas/Respostas da Tela de Questionário

### ISSUE THREAD

**Issue by SteffanoP** [Engenharia-de-Software-UFRPE/lanterna-verde#82]
Atualmente a Tela de Questionário não está no formato mais amigável possível, inicialmente montamos um protótipo em que as perguntas tinham uma ênfase maior que atualmente e o formato de aceitação das perguntas era diferente. Logo proponho uma outra proposta para a tela de questionário onde as perguntas terão uma ênfase maior e também as respostas terão uma ênfase maior.

## Objetivos

- Reestilizar a seção de questões para um novo design
- Implementar a animação de resposta positiva ou negativa para as questões

## Protótipo de Referência

- [Protótipo do Projeto no Figma](https://www.figma.com/file/fhXY06Ja8DtHWySc7vmGYG/Lanterna-Verde?node-id=2%3A2641)
- [Protótipo da animação no Figma](https://www.figma.com/proto/fhXY06Ja8DtHWySc7vmGYG/Lanterna-Verde?node-id=13%3A2856&scaling=min-zoom&page-id=2%3A2641&starting-point-node-id=13%3A2856)
  - Aperte no botão de positivo para a resposta, em seguida no negativo

## Comentários

Creio que por hora não seja necessário se preocupar com Justificativa e Fonte que o Analista precisa dar, vou criar uma outra Issue para mostrar como esses campos podem ser abordados e evitar a necessidade de mostrar Justificativa e Fonte o tempo todo para as perguntas, logo essa Issue não necessariamente se refere a esses campos e se for necessário podemos ocultar esses campos por hora.

**Comment by multi-megaman** [comment]
Eu quero fazer isso!
