### ISSUE TITLE
Criar Barra de Progresso na Tela de Questionário

### ISSUE THREAD

**Issue by SteffanoP** [Engenharia-de-Software-UFRPE/lanterna-verde#83]
A Tela de Questionário não necessariamente mostra o progresso que o Analista precisa fazer ou que está em andamento, uma barra de progresso é importante para o Analista observar o seu progresso na resposta das perguntas. Dessa forma, essa Issue busca endereçar a criação de uma barra de progresso para a tela do questionário, que ficará localizada de forma fixa no final da tela do usuário, como um footer flutuante.

## Objetivos

- Implementar o design de barra de progresso do protótipo do Figma;
- Implementar também a porcentagem;
- Reestilizar os botões de Salvar e Finalizar na barra flutuante.

## Protótipo de Referência

- [Protótipo do Projeto no Figma](https://www.figma.com/file/fhXY06Ja8DtHWySc7vmGYG/Lanterna-Verde?node-id=2%3A2641)
- [Protótipo da animação no Figma](https://www.figma.com/proto/fhXY06Ja8DtHWySc7vmGYG/Lanterna-Verde?node-id=13%3A2856&scaling=min-zoom&page-id=2%3A2641&starting-point-node-id=13%3A2856)
  - Observe o avançar da Barra de Progresso ao responder positivo ou negativo.

**Comment by multi-megaman** [comment]
Eu quero fazer!

**Comment by SteffanoP** [comment]
Uma ideia interessante para tratar isso no back-end, é que ao invés de trabalhar com um booleano que diz se a resposta é positiva ou não, trabalhar com um enumerador com os valores positivo, negativo ou não respondido. Dessa forma, o front-end terá mais liberdade para distinguir o que foi respondido ou não.

Uma segunda ideia para evitar grandes problemas de refatoração no back-end, é trabalhar com um novo atributo booleano no modelo, que poderia ser chamado de `answered`, que por padrão é `False` e se tornará `True` a partir do momento que o analista responde a questão.

**Comment by multi-megaman** [comment]
Olá @SteffanoP estou trabalhando na parte do frontend e até o momento consegui desenvolver este prototipo:
![gif-progress-bar 00_00_00-00_00_30](https://user-images.githubusercontent.com/84993974/197357003-56a20819-0daf-49a0-bae0-fcc82c801565.gif)

Como é possível observar, a barra já está 100% funcional. Ao clicar no botão "teste" (que será removido futuramente, claro) a barra  de progresso é aumentada em 10% até chegar aos 100%.

Para que eu possa dar continuidade e poder abrir uma PR, preciso que alguém do backend faça as alterações propostas por @SteffanoP
