### ISSUE TITLE
Criar Animação para ocultar os campos de Justificativa e Fonte na Tela de Questionário

### ISSUE THREAD

**Issue by SteffanoP** [Engenharia-de-Software-UFRPE/lanterna-verde#86]
Atualmente a Tela de Questionário precisa de pequenos ajustes para um formato mais amigável para o usuário Analista, existe um protótipo montado que demonstra uma forma mais amigável para o Analista preencher sua Justificativa e Fonte. Dessa forma, proponho a implementação de uma animação que oculta esses campos quando o Analista não vê necessidade de preencher tal campo, da mesma forma que, exibe esses campos quando o analista precisar preencher o campo.

## Objetivos

- Exibir/Ocultar os campos de Justificativa e Fonte
- Implementar uma animação para demonstrar os campos

## Protótipo de Referência

- [Protótipo do Projeto no Figma](https://www.figma.com/file/fhXY06Ja8DtHWySc7vmGYG/Lanterna-Verde?node-id=2%3A2641)
- [Protótipo da animação no Figma](https://www.figma.com/proto/fhXY06Ja8DtHWySc7vmGYG/Lanterna-Verde?node-id=323%3A2943&scaling=min-zoom&page-id=2%3A2641&starting-point-node-id=323%3A2943&show-proto-sidebar=1)
  - Aperte no campo da pergunta para exibir os campos de Justificativa e Fonte

**Comment by multi-megaman** [comment]
Eu quero fazer!
