### ISSUE TITLE
[Bug] Não é possível finalizar uma análise que possui mais de 1 analista avaliando

### ISSUE THREAD

**Issue by SteffanoP** [Engenharia-de-Software-UFRPE/lanterna-verde#91]
Acontece que isso é um bug extremamente difícil de ser visualizado se você não possui um entendimento básico do sistema que finaliza as análises. O método `finalizar_analise` do controlador `avaliacaoAnalista` não funciona quando há análises em que existem mais de um analista avaliando, pois quando um analista finaliza uma análise e outros analistas ainda não finalizaram suas análises, esse não consegue finalizar sua análise (~muito louco isso né?~).

Verifiquei que isso está relacionado com a função `gerar_relatorio` do controlador `relatorio`, pois em determinado momento na função `finalizar_analise` requisita que o retorno seja passado pela função `gerar_relatorio`:

```python
def finalizar_analise(request):
    if request.method == 'POST':
        post = request.POST
        data = json.loads(request.body)
        analysis = AvaliacaoAnalista.objects.get(pk=data['analysisid'])
        if analysis.analyst.user == request.user:
            password = data['password']
            matchcheck = check_password(password, request.user.password)
            if matchcheck:
                analysis.status = AvaliacaoAnalista.FINISHED
                analysis.save()
                analysis_request = analysis.analysis_request
                if len(analysis_request.analises.filter(status__in=[AvaliacaoAnalista.PENDING, AvaliacaoAnalista.PROCESSING])) == 0:
                    analysis_request.status = SolicitacaoAnalise.FINISHED
                    analysis_request.save()
                return relatorio.gerar_relatorio(analysis_request)
            return HttpResponse("Senha incorreta, a análise não foi finalizada", status=403)
        return HttpResponse("Você não é o responsável por esta análise", status=403)
    return HttpResponseBadRequest()
```

Porém quando a condição inicial não é verdadeira, não há retorno para a função `gerar_relatorio`, gerando um retorno nulo e impossível de visualizar se você tentar reproduzir o bug:

```python
def gerar_relatorio(analysis_request):
    if analysis_request.status == SolicitacaoAnalise.FINISHED:
        try:
            report, _ = Relatorio.objects.get_or_create(request=analysis_request, company=analysis_request.empresa)
        except IntegrityError:
            return HttpResponse("Um relatório já foi gerado para esta solicitação", status=409)
        analises = AvaliacaoAnalistaSerializer(analysis_request.analises.all(), many=True, context={'request': None})
        data = analises.data
        # Continua a criação do Relatório [...]
        # ...
        
        report.save()
        notificacaoAdm.criar_notificacaoAdm_relatorio(report)
        return HttpResponse("Análise finalizada", status=200)
```

**Comment by ronaldo26rodrigues** [comment]
Opa @SteffanoP, na verdade, o analista consegue sim finalizar sua própria análise.  a verificação seguinte tem relação com o objeto solicitação de análise, aquela que agrupa as análises individuais de cada analista e serve como centro das ações em uma análise geral. Funciona assim: o analista finaliza o seu questionário, que vai ser marcado com o status `FINISHED`, então é feita uma verificação para saber se os outros analistas designados para cuidar daquela solicitação também finalizaram as suas. Quando o método vê que não há mais nenhuma análise individual com o status `PENDING` ou `PROCESSING`, aí sim ele muda o status da Solicitação para `FINISHED`

Na parte que o retorno passa pelo método `criar_relatorio` realmente poderia ser feito de uma forma melhor, o relatório não será gerado até que a solicitação esteja finalizada, mas ficou faltando os devidos feedbacks para tal ação, e talvez fosse bom posicionar melhor a chamada desse método lá em `finalizar_analise`

**Comment by SteffanoP** [comment]
Massa @ronaldo26rodrigues ! Você quer trabalhar nessa Issue?

**Comment by ronaldo26rodrigues** [comment]
> 

Quero sim!

**Comment by SteffanoP** [comment]
> Na parte que o retorno passa pelo método `criar_relatorio` realmente poderia ser feito de uma forma melhor, o relatório não será gerado até que a solicitação esteja finalizada, mas ficou faltando os devidos feedbacks para tal ação, e talvez fosse bom posicionar melhor a chamada desse método lá em `finalizar_analise`

Realmente, trata-se do retorno do método, acredito que esse problema pode ser resolvido tratando melhor o retorno do método `criar_relatorio`.
