### ISSUE TITLE
[Feature] Opção de não respondida para as questões do Analista

### ISSUE THREAD

**Issue by SteffanoP** [Engenharia-de-Software-UFRPE/lanterna-verde#93]
@multi-megaman está trabalhando na parte do frontend e conseguiu desenvolver este prototipo:

![gif-progress-bar 00_00_00-00_00_30](https://user-images.githubusercontent.com/84993974/197357003-56a20819-0daf-49a0-bae0-fcc82c801565.gif)

Como é possível observar, a barra já está 100% funcional. Ao clicar no botão "teste" (que será removido futuramente, claro) a barra  de progresso é aumentada em 10% até chegar aos 100%.

Para que eu possa dar continuidade e poder abrir uma PR, preciso que alguém do backend faça as alterações propostas por @SteffanoP, do qual consiste em implementar um novo sistema que seja possível para o front-end identificar quando que uma questão foi respondida e também se a resposta é verdadeira ou falsa.

A abordagem simples seria criar um novo atributo para o modelo `Questoes` que pode ser chamado de `answered`, que irá identificar se a questão foi respondida ou não.

_Originally posted by @multi-megaman in https://github.com/Engenharia-de-Software-UFRPE/lanterna-verde/issues/83#issuecomment-1287876934_

**Comment by multi-megaman** [comment]
Já estou trabalhando nisso tb Chefia!
